/*
 * This source file was generated by the Gradle 'init' task
 */
package devworks;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;

@SpringBootConfiguration
public class App {
    /*This is sample comment to check the commit on github*/
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
